apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-starter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-starter
  template:
    metadata:
      labels:
        app: hazelcast-starter
    spec:
      containers:
        - name: hazelcast-starter
          image: hazelcast-starter
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-starter
spec:
  type: NodePort
  selector:
    app: hazelcast-starter
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - name: hazelcast
      port: 5701

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list



