apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: hazelcast-starter
build:
  artifacts:
  - image: hazelcast-starter
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-pod.yml